.class public final Lam/b$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lam/b;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation

.annotation runtime Lkk/i0;
    k = 0x3
    mv = {
        0x1,
        0x8,
        0x0
    }
    xi = 0x30
.end annotation


# direct methods
.method public static a(Lam/b;I)[Ljava/lang/Object;
    .locals 0
    .param p0    # Lam/b;
        .annotation build Lyq/d;
        .end annotation
    .end param
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lam/b<",
            "TT;>;I)[TT;"
        }
    .end annotation

    .annotation build Lyq/d;
    .end annotation

    new-instance p0, Lkk/k0;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Lkk/k0;-><init>(Ljava/lang/String;)V

    throw p0
.end method
